[project]
name = "mini-llm-02"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "tiktoken>=0.7.0",
    "torch>=2.5.1",
]
