[project]
name = "MyGPT"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "matplotlib>=3.7.5",
    "tensorflow>=2.12.0",
    "tiktoken>=0.7.0",
    "torch>=2.5.1",
    "tqdm>=4.67.1",
]
